# Generated by Django 3.1.2 on 2020-10-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
